Models/ErrorViewModel.cs
using System;

namespace Edit_Report_in_the_Designer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DesignerController.cs
using Microsoft.AspNetCore.Mvc;
using Stimulsoft.Report;
using Stimulsoft.Report.Mvc;
using Stimulsoft.Report.Components;

using Newtonsoft.Json;

namespace Edit_Report_in_the_Designer.Controllers
{
    public class DesignerController : Controller
    {
        static DesignerController()
        {
            // How to Activate
            //Stimulsoft.Base.StiLicense.Key = "6vJhGtLLLz2GNviWmUTrhSqnO...";
            //Stimulsoft.Base.StiLicense.LoadFromFile("license.key");
            //Stimulsoft.Base.StiLicense.LoadFromStream(stream);
        }

        public IActionResult Index()
        {
      
            return View();
        }
        [HttpPost]
        public IActionResult GetReport()
        {

            var report = new StiReport();
            var value = StiNetCoreHelper.MapPath(this, "Reports/TwoSimpleLists.mrt");
            report.Load(value);


            ApplyDesignRestrictions(report);


            return StiNetCoreDesigner.GetReportResult(this, report);
        }
        [HttpPost]
        public IActionResult DesignerEvent()
        {

            return StiNetCoreDesigner.DesignerEventResult(this);
        }

        private void ApplyDesignRestrictions(StiReport report)
        {
            foreach (StiPage page in report.Pages)
            {

                foreach (StiComponent component in page.GetComponents())
                {
                    component.Restrictions =
                        Stimulsoft.Report.Components.StiRestrictions.None;

                    component.Locked = true;


                }
            }
        }
    }
}

Controllers/EditController.cs
using Microsoft.AspNetCore.Mvc;
using Stimulsoft.Report.Mvc;
using Stimulsoft.Report;

namespace Edit_Report_in_the_Designer.Controllers
{
    public class EditController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetReport()
        {
            var report = new StiReport();
            var value = StiNetCoreHelper.MapPath(this, "Reports/TwoSimpleLists.mrt");
            report.Load(value);
            return StiNetCoreDesigner.GetReportResult(this, report);
        }

        public IActionResult DesignerEvent()
        {
            return StiNetCoreDesigner.DesignerEventResult(this);
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Edit_Report_in_the_Designer.Models;

namespace Edit_Report_in_the_Designer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Designer/Index.cshtml
@using Stimulsoft.Report.Mvc
@using Stimulsoft.Report.Web
@using Stimulsoft.Report.Design
@using Newtonsoft.Json
@{
  ViewBag.Title = "Index";
}

@Html.StiNetCoreDesigner("StiWebDesigner1", new StiNetCoreDesignerOptions {
    Actions = {
        GetReport = "GetReport",
        DesignerEvent = "DesignerEvent"
      },
      PropertiesGrid = {
        Visible = false
      },
      FileMenu = {
        Visible = false,
        ShowReportSetup = false
      },
      Dictionary = {
        Visible = false,
      },
      Toolbar = {
        ShowToolbar = false,
        ShowSetupToolboxButton = false,
        
      },
      Pages = {
        ShowNewPageButton = false

      },
      Dashboards = {
        ShowNewDashboardButton = false
      },
      Appearance = {
        ShowReportTree = false,
      },
      Bands = {
        ShowReportTitleBand = false,
        ShowReportSummaryBand = false,
        ShowPageHeaderBand = false,
        ShowPageFooterBand = false,
        ShowGroupHeaderBand = false,
        ShowGroupFooterBand = false,
        ShowHeaderBand = false,
        ShowFooterBand = false,
        ShowColumnHeaderBand = false,
        ShowColumnFooterBand = false,
        ShowDataBand = false,
        ShowHierarchicalBand = false,
        ShowChildBand = false,
        ShowEmptyBand = false,
        ShowOverlayBand = false,
        ShowTableOfContents = false,
      },
      CrossBands = {
        ShowCrossGroupHeaderBand = false,
        ShowCrossGroupFooterBand = false,
        ShowCrossHeaderBand = false,
        ShowCrossFooterBand = false,
        ShowCrossDataBand = false,
      },
      Components = {
        ShowText = false,
        ShowTextInCells = false,
        ShowRichText = false,
        ShowImage = false,
        ShowBarCode = false,
        ShowShape = false,
        ShowMap=false,
        ShowChart=false,
        ShowGauge=false,
        ShowHorizontalLinePrimitive =false,
        ShowVerticalLinePrimitive=false,
        ShowRectanglePrimitive=false,
        ShowRoundedRectanglePrimitive=false,
        ShowSparkline=false,
        ShowCrossTab=false,
        ShowTable=false,
        ShowClone=false,
        ShowPanel=false,
        ShowCheckBox=false,
        ShowSubReport=false,
        ShowZipCode=false,
      },

      Height = Stimulsoft.System.Web.UI.WebControls.Unit.Pixel(600),

  
  })

  <script >
  jsStiWebDesigner1.onready = function () {
    //1
    console.log(jsStiWebDesigner1)
    jsStiWebDesigner1.options.toolBar.changeVisibleState(false);
    jsStiWebDesigner1.options.toolBar.remove();

    jsStiWebDesigner1.options.workPanel.changeVisibleState(false);
    jsStiWebDesigner1.options.workPanel.remove();

    //2
    jsStiWebDesigner1.InitializeComponentContextMenu = function () {}

    //3
    jsStiWebDesigner1.InitializeRenamePageForm = function () {};

    //4
    jsStiWebDesigner1.InitializePageContextMenu = function () {};

    //5
    jsStiWebDesigner1.InitializePageSetupForm = function () {};
  } 
  </script> 

Views/Edit/Index.cshtml
@using Stimulsoft.Report.Mvc
@using Stimulsoft.Report.Web
@using Stimulsoft.Report.Design

@{
    bool allowEdit = Context.Request.Query["allowEdit"] == "True";
    ViewBag.Title = "Edit Report";
}

@if (allowEdit)
{
    @Html.StiNetCoreDesigner(new StiNetCoreDesignerOptions
{
    Actions =
        {
        GetReport = "GetReport",
        DesignerEvent = "DesignerEvent"
        },
    Height = Stimulsoft.System.Web.UI.WebControls.Unit.Pixel(600)
})
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
@{
    bool allowEdit = Context.Request.Query["allowEdit"] == "True";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Edit Report in the Designer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Report Designer</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @if (!allowEdit)
                        {
                            <a href="@Url.Action("Index", "Edit", new { allowEdit = true })" class="btn btn-primary">
                                Edit Report
                            </a>
                        }

                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="">
        <main role="main" class="pb-3 max-h-80">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>